# Generated by Django 3.0.3 on 2020-02-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestModel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.CharField(max_length=200)),
                ('data2', models.CharField(max_length=200)),
                ('data3', models.CharField(max_length=200)),
            ],
        ),
    ]
