# Generated by Django 3.0.3 on 2020-02-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_app', '0002_restmodel2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restmodel2',
            old_name='data1',
            new_name='this is data1',
        ),
    ]
